# Settings
settingsRan: false
logMessages: true
logDays: 7
logSaveSeconds: 300
excludedTabs:
  - vanillatweaks
  - custom_nether_portals

# Point tracking toggle
trackPoints:
  adv: true
  fish: false
  mob: false
  purge: false
  break: false
  place: false

# Placeholders
placeholders:
  - "adv"
  - "fish"
  - "mob"
  - "purge"
  - "break"
  - "place"

# Points to award
challenge: 45
goal: 25
task: 10

# Cooldowns in minutes
purgeCooldown: 30
respawnCooldown: 15
notify: true

# Speed of 1.0 is normal speed
daySpeed: 1.0
nightSpeed: 1.0
enableTimeWarp: false

# Add blocks to ignore here, e.g. "STONE"
ignoredBlocks:
  - "air"
