name: CatsTracker
version: '${project.version}'
main: io.github.cats1337.CatsTracker.CatsTracker
api-version: '1.21'
authors:
  - Cats1337
description: CatsTracker tracks points for stuff
depend: [PlaceholderAPI] #required for placeholders and such
softdepend: [DecentHolograms, CoreProtect] # DecentHolograms: optional for holograms | CoreProtect: required for block tracking